# Generated by Django 2.1.5 on 2019-04-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('duration_from', models.PositiveIntegerField(blank=True, default=0)),
                ('duration_to', models.PositiveIntegerField(blank=True, default=5)),
            ],
        ),
    ]
