# Generated by Django 2.1.5 on 2019-04-15 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0004_auto_20190415_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='food_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cooking.FoodCategory'),
            preserve_default=False,
        ),
    ]
