# Generated by Django 2.1.5 on 2019-04-15 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0006_auto_20190415_1020'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeIngredients',
            new_name='RecipeIngredient',
        ),
        migrations.RenameModel(
            old_name='RecipeProcedures',
            new_name='RecipeProcedure',
        ),
    ]
